name: Build and Deploy VitePress

on:
  push:
    branches:
      - main   # 每次 push 到 main 就自动部署

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 安装 PNPM
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # 安装 Node + PNPM 缓存
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 构建 VitePress 文档
      - name: Build VitePress website
        run: pnpm run docs:build

      # 上传 dist 构建结果到服务器
      - name: Upload dist to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docs/.vitepress/dist/."
          target: "/www/wwwroot/www.seeuui.cn"
